name: CI

on: [push]

jobs:
    check:
        name: Check Syntax
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: sudo make build-deps
            - name: Run Checks
              run: make check
